<a href="https://colab.research.google.com/github/iamclowdee/Student-Placement-Prediction-ML-IPYNB-/blob/main/Student_Placement_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Cell 1: Import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

print("All libraries imported successfully!")

All libraries imported successfully!

In [4]:
#Cell 2: Dummy dataset

import pandas as pd

data = {
    "CGPA":[8.9,8.5,9.1,7.8,8.2,6.5,6.8,7.0,7.2,7.4],
    "Internships":[3,2,4,1,2,0,0,1,1,1],
    "Projects":[5,4,6,3,4,1,2,2,3,3],
    "Workshops":[4,3,5,2,3,1,1,1,2,2],
    "AptitudeTestScore":[92,88,95,75,82,55,58,62,65,68],
    "SoftSkillsRating":[9,8,10,7,8,5,5,6,6,7],
    "PlacementStatus":[1,1,1,1,1,0,0,0,0,0]
}

df = pd.DataFrame(data)

df.to_csv("placement.csv", index=False)

print("placement.csv created successfully!")

placement.csv created successfully!

In [5]:
# Cell 3: Load dataset

# FileNotFoundError: The file 'placement.csv' was not found. Please ensure the file is uploaded
# to your Colab environment or provide the correct path to the file.
df = pd.read_csv("placement.csv")

print("Dataset Loaded Successfully!")

df.head()

Dataset Loaded Successfully!

,CGPA,Internships,Projects,Workshops,AptitudeTestScore,SoftSkillsRating,PlacementStatus
0,8.9,3,5,4,92,9,1
1,8.5,2,4,3,88,8,1
2,9.1,4,6,5,95,10,1
3,7.8,1,3,2,75,7,1
4,8.2,2,4,3,82,8,1

In [6]:
# Cell 4: Explore Data

print("Shape:", df.shape)

print("\nPlacement Count:\n")
print(df["PlacementStatus"].value_counts())

print("\nMissing Values:\n")
print(df.isnull().sum())

df.describe()

Shape: (10, 7)

Placement Count:

PlacementStatus
1    5
0    5
Name: count, dtype: int64

Missing Values:

CGPA                 0
Internships          0
Projects             0
Workshops            0
AptitudeTestScore    0
SoftSkillsRating     0
PlacementStatus      0
dtype: int64

,CGPA,Internships,Projects,Workshops,AptitudeTestScore,SoftSkillsRating,PlacementStatus
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000
mean,7.740000,1.500000,3.300000,2.400000,74.000000,7.10000,0.500000
std,0.904556,1.269296,1.494434,1.349897,14.544949,1.66333,0.527046
min,6.500000,0.000000,1.000000,1.000000,55.000000,5.00000,0.000000
25%,7.050000,1.000000,2.250000,1.250000,62.750000,6.00000,0.000000
50%,7.600000,1.000000,3.000000,2.000000,71.500000,7.00000,0.500000
75%,8.425000,2.000000,4.000000,3.000000,86.500000,8.00000,1.000000
max,9.100000,4.000000,6.000000,5.000000,95.000000,10.00000,1.000000